example:
  image: test
  ports:
    - 80:80
    - 443:443
  environment:
    - APACHE_MOD_PROXY=
        ProxyRequests On \n
        SSLProxyEngine On \n
        ProxyPass / https://www.linkedin.com/in/andreluiznsilva \n